[package]
name = "zcash-wallet-sdk-poc"
version = "0.0.1"
authors = ["Kevin Gorham <kevin.gorham@z.cash>"]
description = "Simple PoC that rust can work with protobufs over JNI"
publish = false

[dependencies]
rand = "0.4"
rusqlite = { version = "0.15", features = ["bundled"] }
log = "0.4"

[dependencies.zcash_client_backend]
git = "https://github.com/str4d/librustzcash.git"
rev = "63ec78bb857a258a97d25a5a6e747389996e566a"

[dependencies.zip32]
git = "https://github.com/str4d/librustzcash.git"
rev = "63ec78bb857a258a97d25a5a6e747389996e566a"

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.10", default-features = false }
android_logger = "0.6"
log-panics = "2.0.0"

[lib]
name = "zcashwalletsdk"
path = "src/main/rust/lib.rs"
crate-type = ["staticlib", "cdylib"]
